version: "3.8"
services:
  mysql:
    image: mysql:8.4.3
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password_here  # Replace with your root password
      MYSQL_DATABASE: example_db  # Initial database name
      MYSQL_USER: root  # Replace with your desired MySQL user
      MYSQL_PASSWORD: user_password_here  # Replace with your desired user password
    ports:
      - "3306:3306"  # Expose MySQL on port 3306
    volumes:
      - mysql_data:/var/lib/mysql  # Persist MySQL data
    restart: unless-stopped

volumes:
  mysql_data: